name: Deploy da Aplicação Python

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: buildx-latest
    steps:
      - name: Verificar código
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Buildar e publicar imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fiap-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fiap-app:latest

  deploy:
    runs-on: buildx-latest
    needs: build
    steps:
      - name: Fazer login no DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Baixar e executar a imagem Docker
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/fiap-app:latest
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/fiap-app:latest
